export const templates = [
  {
    id: 'react',
    name: 'React',
    category: 'frontend',
    language: 'TypeScript',
    framework: 'TanStack Start',
    description: 'Complete React starter with Pubflow integration.',
    repo: 'pubflow/react-flowfull-client',
    branch: 'master',
    installCommand: 'bun install',
    devCommand: 'bun run dev',
  },
  {
    id: 'react-native',
    name: 'React Native Expo',
    category: 'frontend',
    language: 'TypeScript',
    framework: 'Expo',
    description: 'Cross-platform mobile starter for iOS and Android.',
    repo: 'pubflow/create-pubflow-rn',
    branch: 'master',
    installCommand: 'npm install',
    devCommand: 'npx expo start',
  },
  {
    id: 'next',
    name: 'Next.js',
    category: 'frontend',
    language: 'TypeScript',
    framework: 'Next.js',
    description: 'Next.js starter with Pubflow auth, 2FA, dashboard, i18n, and shadcn UI.',
    repo: 'pubflow/next-flowfull-client',
    branch: 'main',
    installCommand: 'npm install',
    devCommand: 'npm run dev',
  },
  {
    id: 'node-backend',
    name: 'Node.js Backend',
    category: 'backend',
    language: 'TypeScript',
    framework: 'Flowfull',
    description: 'Official Node.js / TypeScript Flowfull backend starter.',
    repo: 'pubflow/flowfull-node',
    branch: 'master',
    installCommand: 'npm install',
    devCommand: 'npm run dev',
  },
  {
    id: 'python-backend',
    name: 'Python Backend',
    category: 'backend',
    language: 'Python',
    framework: 'FastAPI',
    description: 'Flowfull backend starter powered by Python and FastAPI.',
    repo: 'pubflow/flowfull-python-starter',
    branch: 'master',
    installCommand: 'pip install -r requirements.txt',
    devCommand: 'uvicorn app.main:app --reload --host 0.0.0.0 --port 3001',
  },
  {
    id: 'go-backend',
    name: 'Go Backend',
    category: 'backend',
    language: 'Go',
    framework: 'Gin',
    description: 'Flowfull backend starter for high-performance Go APIs.',
    repo: 'pubflow/flowfull-go-starter',
    branch: 'master',
    installCommand: 'go mod download',
    devCommand: 'go run cmd/server/main.go',
  },
  {
    id: 'rust-backend',
    name: 'Rust Backend',
    category: 'backend',
    language: 'Rust',
    framework: 'Axum',
    description: 'Flowfull backend starter powered by Rust, Axum, Tokio, and SQLx.',
    repo: 'pubflow/flowfull-rust-starter',
    branch: 'master',
    installCommand: 'cargo fetch',
    devCommand: 'cargo run',
  },
  {
    id: 'elixir-backend',
    name: 'Elixir Backend',
    category: 'backend',
    language: 'Elixir',
    framework: 'Flowfull',
    description: 'Flowfull backend starter for Elixir applications.',
    repo: 'pubflow/flowfull-elixir-starter',
    branch: 'master',
    installCommand: 'mix deps.get',
    devCommand: 'mix phx.server',
  },
  {
    id: 'native',
    name: 'Pubflow Native',
    category: 'fullstack',
    language: 'TypeScript',
    framework: 'Hono + React',
    description: 'Default: React pages + Hono API, auth, Tailwind, Docker, Cloudflare.',
    repo: 'pubflow/native',
    branch: 'master',
    rootDir: 'starter',
    installCommand: 'bun install',
    devCommand: 'bun run dev',
  },
  {
    id: 'native-minimal',
    name: 'Pubflow Native (Minimal)',
    category: 'fullstack',
    language: 'TypeScript',
    framework: 'Hono + React',
    description: 'No auth, no Tailwind. One page and /api/hello.',
    repo: 'pubflow/native',
    branch: 'master',
    rootDir: 'examples/minimal',
    installCommand: 'bun install',
    devCommand: 'bun run dev',
  },
  {
    id: 'native-custom-hono',
    name: 'Pubflow Native (Custom Hono)',
    category: 'fullstack',
    language: 'TypeScript',
    framework: 'Hono + React',
    description: 'You own app/server.ts and mount pages, API, and actions.',
    repo: 'pubflow/native',
    branch: 'master',
    rootDir: 'examples/custom-hono-server',
    installCommand: 'bun install',
    devCommand: 'bun run dev',
  },
];

const TEMPLATE_ALIASES = {
  flowloft: 'native',
  flowstack: 'native',
  'pubflow-native': 'native',
  'custom-hono': 'native-custom-hono',
  'native-custom-hono-server': 'native-custom-hono',
};

export function getTemplate(id) {
  const resolved = TEMPLATE_ALIASES[id] || id;
  return templates.find((template) => template.id === resolved);
}

export function getTemplatesByCategory(category) {
  return templates.filter((template) => template.category === category);
}
